name: Build Container Images

on:
  push:
    tags:
      - v*
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
    
jobs:
  build_containers:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Create Artifacts Directory
        run: mkdir artifacts
      - name: Install Apptainer
        run: |
          .github/scripts/install_apptainer.sh
      - name: Check Apptainer installation
        run: apptainer --version
      - name: Install Wave CLI
        run: |
          .github/scripts/install_wave-cli.sh
      - name: Check wave installation
        run: wave --version
      - name: Build images
        run: |
          .github/scripts/build_container_images_wave.sh
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: artifacts-BCCDC-PHL-basic-sequence-qc-build-containers-${{ github.run_id }}.${{ github.run_attempt }}
          path: artifacts
